<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Customers';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="customers-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Customers', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'timestamp',
            'No_',
            'Name',
            'Phone No_',
            'Address',
            // 'Address',
            // 'Address 2',
            // 'City',
            // 'Contact',
            // 'Phone No_',
            // 'Telex No_',
            // 'Our Account No_',
            // 'Territory Code',
            // 'Global Dimension 1 Code',
            // 'Global Dimension 2 Code',
            // 'Chain Name',
            // 'Budgeted Amount',
            // 'Credit Limit (LCY)',
            // 'Customer Posting Group',
            // 'Currency Code',
            // 'Customer Price Group',
            // 'Language Code',
            // 'Statistics Group',
            // 'Payment Terms Code',
            // 'Fin_ Charge Terms Code',
            // 'Salesperson Code',
            // 'Shipment Method Code',
            // 'Shipping Agent Code',
            // 'Place of Export',
            // 'Invoice Disc_ Code',
            // 'Customer Disc_ Group',
            // 'Country_Region Code',
            // 'Collection Method',
            // 'Amount',
            // 'Blocked',
            // 'Invoice Copies',
            // 'Last Statement No_',
            // 'Print Statements',
            // 'Bill-to Customer No_',
            // 'Priority',
            // 'Payment Method Code',
            // 'Last Date Modified',
            // 'Application Method',
            // 'Prices Including VAT',
            // 'Location Code',
            // 'Fax No_',
            // 'Telex Answer Back',
            // 'VAT Registration No_',
            // 'Combine Shipments',
            // 'Gen_ Bus_ Posting Group',
            // 'Picture',
            // 'Post Code',
            // 'County',
            // 'E-Mail',
            // 'Home Page',
            // 'Reminder Terms Code',
            // 'No_ Series',
            // 'Tax Area Code',
            // 'Tax Liable',
            // 'VAT Bus_ Posting Group',
            // 'Reserve',
            // 'Block Payment Tolerance',
            // 'IC Partner Code',
            // 'Prepayment _',
            // 'Partner Type',
            // 'Preferred Bank Account',
            // 'Cash Flow Payment Terms Code',
            // 'Primary Contact No_',
            // 'Responsibility Center',
            // 'Shipping Advice',
            // 'Shipping Time',
            // 'Shipping Agent Service Code',
            // 'Service Zone Code',
            // 'Allow Line Disc_',
            // 'Base Calendar Code',
            // 'Copy Sell-to Addr_ to Qte From',
            // 'ParentID',
            // 'SponsorID',
            // 'Withholding Tax Code',
            // 'PIN No_',
            // 'DateOfIncorporation',
            // 'CountyID',
            // 'UserID',
            // 'RegistrationDate',
            // 'Mobile 1',
            // 'Mobile 2',
            // 'Gender',
            // 'Date Of Birth',
            // 'Age',
            // 'Marital Status',
            // 'Weight',
            // 'Height',
            // 'Religion',
            // 'Citizenship',
            // 'Student Type',
            // 'ID No',
            // 'Sponsor Type',
            // 'Customer Type',
            // 'Birth Cert',
            // 'remove 2',
            // 'test to remove later',
            // 'Status',
            // 'Library Code',
            // 'KNEC No',
            // 'Passport No',
            // 'Confirmed Ok',
            // 'Library Membership',
            // 'libsecurity',
            // 'Can Use Library',
            // 'Lib Membership',
            // 'Staff No_',
            // 'Programme Category',
            // 'Application No_',
            // 'Accredited Centre no_',
            // 'Adults',
            // 'Vehicle No_',
            // 'Children Under 12',
            // 'Group_Company',
            // 'Departure Date',
            // 'Arrival Date',
            // 'Nationality',
            // 'Room no',
            // 'Room Type',
            // 'Receipt No',
            // 'Rate',
            // 'Cashier',
            // 'Deposit',
            // 'Payment Date',
            // 'Remarks',
            // 'Guest Agent Code',
            // 'Taken By',
            // 'Checked By',
            // 'HTL Status',
            // 'HELB No_',
            // 'Deferement Period',
            // 'Status Change Date',
            // 'Revenue Cash Account',
            // 'Certificate Status',
            // 'Date Collected',
            // 'Confirmed',
            // 'Confirmed Remarks',
            // 'Special Requrements',
            // 'Certificate No_',
            // 'District',
            // 'Transfer to No_',
            // 'Transfer to',
            // 'Current Programme',
            // 'Paid PartTime:datetime',
            // 'Hostel Black Listed',
            // 'Black Listed Reason',
            // 'Black Listed By',
            // 'Audit Issue',
            // 'Not Billed',
            // 'New Stud',
            // 'Lock Online Application',
            // 'Entry Semester',
            // 'Intake',
            // 'Date Registered',
            // 'StudentOrMember',
            // 'Salutation',
            // 'Select',
            // 'SentForCommittee',
            // 'DateSentForCommittee',
            // 'CommitteeApprovalStatus',
            // 'CommitteeApprovalDate',
            // 'CommitteeMinuteNo',
            // 'Mode of Study',
            // 'State',
            // 'Local Government Authority',
            // 'Clearance Status',
            // 'Clearance Initiated by',
            // 'Clearance Initiated Date',
            // 'Clearance Initiated Time',
            // 'Clearance Semester',
            // 'Clearance Academic Year',
            // 'Intake Code',
            // 'Programme End Date',
            // 'Applied for Clearance',
            // 'Clearance Reason',
            // 'Barcode Picture',
            // 'ID Card Expiry Year',
            // 'Graduated',
            // 'Graduation Date',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>
